---
- name: firewall rules directory exists
  file:
    path: /etc/firewall
    state: directory
    mode: 0640
    owner: root
    group: root
  become: true

- name: firewall rules generated
  template:
    dest: /etc/firewall/rules.{{ item  }}
    src: templates/firewall/rules.{{ item }}
  loop:
    - ipv4
    - ipv6
  notify: firewall services restarted
  become: true
  
    