---
- name: firewall service configurations uploaded
  copy:
    dest: /etc/systemd/system/firewall-{{ item }}.service
    src: templates/etc/systemd/system/firewall-{{ item }}.service
  loop:
    - ipv4
    - ipv6
  notify: systemctl daemon reloaded

- name: firewall services enabled
  service:
    name: firewall-{{ item }}.service
    enabled: yes
  loop:
    - ipv4
    - ipv6
  notify: firewall services restarted
  become: true
  
